/**:
  ros__parameters:
    fcu_url: "udp://:14540@127.0.0.1:14557"
    gcs_url: ""
    target_system_id: 1
    target_component_id: 1
    fcu_protocol: "v2.0"
    # https://docs.px4.io/v1.12/en/simulation/failsafes.html
    NAV_DLL_ACT: 0
    NAV_RCL_ACT: 0
    COM_RCL_EXCEPT: 4
